// Standalone helper: writes the compiled artifact's ABI into the Next.js app
// as a fully-typed `as const` array, so the frontend can never drift from the
// deployed bytecode.
//
//   npm --prefix contracts run compile && node contracts/scripts/export-abi.js
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "../..");
const ARTIFACT_DIR = path.join(ROOT, "contracts/artifacts");
const OUT = path.join(ROOT, "lib/abi.ts");

/** Locate `AegisCallZK.json` wherever hardhat put it (it mirrors the source path). */
function findArtifact(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const hit = findArtifact(full);
      if (hit) return hit;
    } else if (entry.name === "AegisCallZK.json" && !entry.name.endsWith(".dbg.json")) {
      return full;
    }
  }
  return null;
}

if (!fs.existsSync(ARTIFACT_DIR)) {
  console.error(`[export-abi] no artifacts directory at ${ARTIFACT_DIR}\n  run "npm run compile" first.`);
  process.exit(1);
}

const ARTIFACT = findArtifact(ARTIFACT_DIR);
if (!ARTIFACT) {
  console.error('[export-abi] could not find artifacts/**/AegisCallZK.json\n  run "npm run compile" first.');
  process.exit(1);
}

const { abi, contractName } = JSON.parse(fs.readFileSync(ARTIFACT, "utf8"));

const banner = `/**
 * AUTO-GENERATED by contracts/scripts/export-abi.js — do not edit by hand.
 *
 * ABI for ${contractName}. Regenerate with:
 *   npm run contract:compile && node contracts/scripts/export-abi.js
 */\n`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(
  OUT,
  `${banner}\nexport const aegisCallZkAbi = ${JSON.stringify(abi, null, 2)} as const;\n`,
  "utf8",
);

console.log(`[export-abi] wrote ${path.relative(ROOT, OUT)} (${abi.length} entries)`);
